import React, { useState, useEffect, ChangeEvent } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

/* next js */
import Link from 'next/link';

/* icons */
import { MdFacebook } from "react-icons/md";

/* components */
import { NormalInput, NormalButton } from "../components";

const Home: NextPage = () => {
  const [inputs, setInputs] = useState({
    email: "",
    password: "",
  });

  const handleInputChange = (
    event: ChangeEvent<HTMLTextAreaElement | HTMLInputElement>
  ) => {
    setInputs((prevState) => ({
      ...prevState,
      [event.target.name]: event.target.value,
    }));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>LikeShoes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Accede</h1>

        <p className={styles.description}>Inicia sesion para continuar</p>

        <section className={styles.grid}>
          <div className={styles.inputContainer}>
            <NormalInput
              label="Correo electronico"
              value={inputs.email}
              name="email"
              handleInputChange={handleInputChange}
            />
          </div>

          <div className={styles.inputContainer}>
            <NormalInput
              label="Contraseña"
              value={inputs.password}
              name="password"
              type="password"
              handleInputChange={handleInputChange}
            />
          </div>

          <div className={styles.buttonContainer}>
            <NormalButton value="Inciar sesión" />
          </div>

          <div className={styles.separador}>
            <div className={styles.separadorInterno}></div>
            <p>O</p>
            <div className={styles.separadorInterno}></div>
          </div>

          <div className={styles.facebook}>
            <MdFacebook size={25} color="#385185" style={{ width: "10%" }} />
            <p style={{ width: "90%", color: "#385185", marginLeft: 5, fontWeight: "bold" }}>Inicia sesión con facebook</p>
          </div>

          <div className={styles.iniciarConRedesSociales}></div>


          <Link href="/Register">¿No tienes una cuenta? click aqui para registrarte</Link>

          <div className={styles.buttonContainer}></div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Servicio nacional de aprendizaje SENA
        </a>
      </footer>
    </div>
  );
};

export default Home;
